AWSTemplateFormatVersion: "2010-09-09"
Description: Boomi Atom Installation Script. This creates a VPC, Public Subnets and Private Subnets, and stages a Dell Boomi Atom.
Parameters:
  KeyName:
    Description: Keyname for access to EC2 Instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing Keyname
  AtomInstanceType:
    Description: Boomi Host Instance Type
    Type: String
    Default: m5.xlarge
    AllowedValues:
      - m4.xlarge
      - m5.xlarge
      - r4.xlarge
      - r5.xlarge
  AtomInstanceVolumeSize:
     Description: Atom Volume Size (In GiB)
     Type: Number
     Default: 100
  EnvironmentName:
    Description: A Name that will be prefixed to resource names
    Type: String
    Default: Boomi
  VPCCIDR:
    Description: Please enter the IP Range (CIDR notation) for this VpcCIDR
    Type: String
    Default: 172.30.0.0/16
  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 172.30.1.0/28
  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 172.30.1.16/28
  PublicSubnet3CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 172.30.1.32/28
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 172.30.5.0/24
  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 172.30.6.0/24
  PrivateSubnet3CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 172.30.7.0/24
  BoomiUserName:
    Description: Please enter your Boomi User Name
    Type: String
  BoomiPassword:
     Description: Please enter your Boomi Account Password
     Type: String
  BoomiAccountID:
     Description: Please enter your Boomi Account ID
     Type: String
  InstallDirectory:
     Description: Please enter an install InstallDirectoryectory for Boomi
     Type: String
     Default: /usr/local/boomi
  AtomInstanceName:
     Description: Please enter a name for your Boomi Instance
     Type: String
     Default: atom1
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters:
         - EnvironmentName
         - VPCCIDR
         - PublicSubnet1CIDR
         - PublicSubnet2CIDR
         - PublicSubnet3CIDR
         - PrivateSubnet1CIDR
         - PrivateSubnet2CIDR
         - PrivateSubnet3CIDR
      - 
        Label: 
          default: "Amazon EC2 Configuration"
        Parameters: 
          - AtomInstanceType
          - KeyName
          - OS
          - AtomInstanceVolumeSize
      -
        Label:
          default: "Dell Boomi Atom Configuration"
        Parameters:
         - AtomInstanceName
         - BoomiAccountID
         - BoomiUserName
         - BoomiPassword
         - InstallDirectory
Mappings:
  AWSAMIRegionMap:
    AMI:
      AMZNLINUXHVM: amzn-ami-hvm-2018.03.0.20180811-x86_64-gp2
    us-east-1:
      AMZNLINUXHVM: ami-0ff8a91507f77f867
    us-west-2:
      AMZNLINUXHVM": ami-0b59bfac6be064b78
Resources:
  BoomiSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow SSH to Bastion Host
            VpcId:
                Ref: VPCID
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: '22'
                ToPort: '22'
                CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
              - IpProtocol: -1
                CidrIp: 0.0.0.0/0
            Tags:
              - Key: Name
                Value: Boomi Instance Security Group
  AtomInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
       - AWSAMIRegionMap
       - Ref: AWS::Region
       - Ref: AMZNLINUXHVM
      InstanceType:
        Ref: InstanceType
      BlockDeviceMappings: 
       - DeviceName: "/dev/xvda"
         Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "false"
          VolumeSize:
            Ref: "AtomInstanceVolumeSize"
      UserData:
       Fn::Base64: !Sub |
             #!/bin/bash -ex
             yum install -y python-setuptools
             yum install -y wget
             mkdir -p /opt/aws/bin
             wget https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
             easy_install --script-dir /opt/aws/bin aws-cfn-bootstrap-latest.tar.gz
             /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource AtomInstance --configsets quickstart --region ${AWS::Region}
             /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AtomInstance --region ${AWS::Region}
      KeyName:
        Ref: KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: "BoomiSecurityGroup"
          SubnetId:
            Ref: "PublicSubnet1"
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          quickstart:
            - create_structure
            - install_boomi_atom
            - verify_boomi_running
        create_structure:
          commands:
            01_create_boomi_installdir:
              command: mkdir -p /usr/local/boomi
        install_boomi_atom:
          commands:
            01_fetch_install_script:
              command: wget -O /root/boomi-atom-installer.sh https://platform.boomi.com/atom/atom_install64.sh
            02_fix_permissions:
              command: chmod +x /root/boomi-atom-installer.sh
            03_run_installer:
              commmand: !Sub |
                "/root/boomi-atom-installer.sh  -q console -Vusername=${BoomiUserName} -Vpassword=${BoomiPassword}  -AtomInstanceName=${AtomInstanceName} -BoomiAccountID=${BoomiAccountID} -InstallDirectory=${InstallDirectory}"
        verify_boomi_running:
          commands:
            (...)
Outputs:
  InstanceID:
    Description: The Instance ID of the Bastion Bastion Host
    Value: !Ref AtomInstance