---
AWSTemplateFormatVersion: '2010-09-09'
Description: Boomi Atom Installation Script. This creates a VPC, Public Subnets and
  Private Subnets, and stages a Dell Boomi Atom. (qs-1r0e5j2b9)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPCID
      - PublicSubnet1ID
      - PublicSubnet2ID
      - PrivateSubnet1ID
      - PrivateSubnet2ID
      - BastionSecurityGroupID
    - Label:
        default: Amazon EC2 configuration
      Parameters:
      - InstanceType
      - KeyPairName
      - BoomiInstanceVolumeSize
    - Label:
        default: Dell Boomi Atom configuration
      Parameters:
      - AtomName
      - BoomiAccountID
      - BoomiUsername
      - BoomiPassword
      - BoomiInstallDir
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3KeyPrefix
      - QSS3BucketName
    ParameterLabels:
      KeyPairName:
        default: SSH key name
      PrivateSubnet1CIDR:
        default: Private subnet 1 ID
      PrivateSubnet2CIDR:
        default: Private subnet 2 ID
      PublicSubnet1CIDR:
        default: Public subnet 1 ID
      PublicSubnet2CIDR:
        default: Public subnet 2 ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      RemoteAccessCIDR:
        default: Allowed external access CIDR (OCP UI)
      VPCID:
        default: VPC ID
      VPCCIDR:
        default: VPC CIDR
      InstanceType:
        default: Boomi Atom instance type
      BoomiInstanceVolumeSize:
        default: EBS Volume size for Boomi Atom instance
      BoomiAccountID:
        default: Boomi account ID
      BoomiUsername:
        default: Boomi Username - Not needed if authenticating via installation token
      BoomiPassword:
        default: Boomi password
      BoomiInstallToken:
        Description: Please enter your Boomi Install Token - Not needed if authenticating via BoomiUsername/Password
        Type: String
      AtomName:
        Description: Please enter a name for your Boomi Instance
        Type: String
        Default: atom1
      BoomiInstallDir:
        default: Boomi install directory
Parameters:
  KeyPairName:
    Description: A public/private key pair, which allows you to connect securely to
      your instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing Keyname
  BastionSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
  InstanceType:
    Description: The instance type of the Boomi host. You can choose a different instance
      type from the drop-down list of instances that meet the requirements for running
      a Dell Boomi Atom server.
    Type: String
    Default: m5.xlarge
    AllowedValues:
      - m4.xlarge
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - r4.xlarge
      - r5.xlarge
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
  BoomiInstanceVolumeSize:
    Description: The size of the Amazon EBS volume attached to the Atom instance.
      Size range is 1 GiB - 16 TiB.
    Type: Number
    Default: 100
  VPCID:
    Description: Select the VPC to deploy into.
    Type: AWS::EC2::VPC::Id
  PublicSubnet1ID:
    Description: The ID of the public subnet in Availability Zone 1 in your existing
      VPC.
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2ID:
    Description: The ID of the public subnet in Availability Zone 2 in your existing
      VPC.
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet1ID:
    Description: The ID of the private subnet in Availability Zone 1 in your existing
      VPC.
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: The ID of the private subnet in Availability Zone 1 in your existing
      VPC.
    Type: AWS::EC2::Subnet::Id
  BoomiUsername:
    Description: The email account associated with the Dell Boomi account.
    Type: String
  BoomiPassword:
    Description: Please enter your Boomi Account Password
    Type: String
    NoEcho: true
  BoomiAccountID:
    Description: The Dell Boomi account ID that you want to associate the new Atom
      with.
    Type: String
  BoomiInstallDir:
    Description: The installation directory for Dell Boomi.
    Type: String
    Default: /opt/boomi/
  AtomName:
    Description: The name given to the Boomi Atom instance.
    Type: String
    Default: atom1
  BoomiInstallToken:
    Description: Please enter your Boomi Install Token
    Type: String

Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      AMZNLINUX2HVM: ami-06ad9296e6cf1e3cf2
    ap-northeast-2:
      AMZNLINUX2HVM: ami-0e92198843e11ccee
    ap-south-1:
      AMZNLINUX2HVM: ami-0732b62d310b80e97
    ap-southeast-1:
      AMZNLINUX2HVM: ami-0adbe59da7d24a349
    ap-southeast-2:
      AMZNLINUX2HVM: ami-0a58e22c727337c51
    ca-central-1:
      AMZNLINUX2HVM: ami-05de9e98f3bef5e8a
    eu-central-1:
      AMZNLINUX2HVM: ami-00edb93a4d68784e3
    eu-west-1:
      AMZNLINUX2HVM: ami-0c3e74fa87d2a4227
    eu-west-2:
      AMZNLINUX2HVM: ami-04122be15033aa7ec
    eu-west-3:
      AMZNLINUX2HVM: ami-0bfddfb1ccc3a6993
    sa-east-1:
      AMZNLINUX2HVM: ami-081a078e835a9f751
    us-east-1:
      AMZNLINUX2HVM: ami-08f3d892de259504d
    us-east-2:
      AMZNLINUX2HVM: ami-016b213e65284e9c9
    us-west-1:
      AMZNLINUX2HVM: ami-01311df3780ebd33e
    us-west-2:
      AMZNLINUX2HVM: ami-0b1e2eeb33ce3d66f
    eu-north-1:
      AMZNLINUX2HVM: ami-07d2cd50077a70430
    ap-east-1:
      AMZNLINUX2HVM: ami-c85919b9
    me-south-1:
      AMZNLINUX2HVM: ami-07f5fe2b1e463e06a
    af-south-1:
      AMZNLINUX2HVM: ami-08b08c0713ffd89ef
    eu-south-1:
      AMZNLINUX2HVM: ami-01ce136ac703e9899
    ap-northeast-3:
      AMZNLINUX2HVM: ami-0eed4f60edb4a77f8
    us-gov-east-1:
      AMZNLINUX2HVM: ami-9a033cfb
    us-gov-west-1:
      AMZNLINUX2HVM: ami-a2729dde
    cn-north-1:
      AMZNLINUX2HVM: ami-0aec3e46a106ca42d
    cn-northwest-1:
      AMZNLINUX2HVM: ami-05a85395c8ff37b18

Rules:
  PasswordOrMFAToken:
    Assertions:
      - Assert: !Or
          - !And
            - !Equals [!Ref BoomiPassword, '']
            - !Not [!Equals [!Ref BoomiInstallToken, '']]

          - !And
            - !Not [!Equals [!Ref BoomiPassword, '']]
            - !Equals [!Ref BoomiInstallToken, '']
        AssertDescription: You must supply either a password *or* an MFA installation token.
Conditions:
  InstallTokenProvided:  !Not [!Equals [!Ref BoomiInstallToken, '']]

Resources:
  BoomiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: boomi
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: BoomiSG
      SecurityGroupIngress:
      - FromPort: 22
        IpProtocol: tcp
        SourceSecurityGroupId: !Ref BastionSecurityGroupID
        ToPort: 22
  AtomInstanceEBS:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref BoomiInstanceVolumeSize
      Encrypted: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: Atom
    DeletionPolicy: Snapshot

  AtomInstance:
    DependsOn: BoomiSecurityGroup
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: Name
          Value: !Ref 'AtomName'
      ImageId:
        !FindInMap
        - AWSAMIRegionMap
        - Ref: AWS::Region
        - AMZNLINUX2HVM
      InstanceType:
        Ref: InstanceType
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      NetworkInterfaces:
        - GroupSet:
            - !Ref BoomiSecurityGroup
          AssociatePublicIpAddress: 'false'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PrivateSubnet1ID
      Volumes:
        -
          Device: "/dev/xvdf"
          VolumeId: !Ref AtomInstanceEBS

      KeyName:
        Ref: KeyPairName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          if [ $UID -eq 0 ]; then
            sudo chmod 777 "$0"
            exec su ec2-user "$0"
          fi
          export PATH=$PATH:/usr/local/bin
          sudo yum install git -y || apt-get install -y git || zypper -n install git
          sudo git clone https://github.com/aws-quickstart/quickstart-linux-utilities.git /quickstart-linux-utilities
          cd /quickstart-linux-utilities
          source quickstart-cfn-tools.source
          qs_update-os
          qs_aws-cfn-bootstrap
          sudo cfn-init -v --stack ${AWS::StackName} --resource AtomInstance --region ${AWS::Region}
          sudo cfn-signal -e $? --stack ${AWS::StackName} --resource AtomInstance --region ${AWS::Region}

    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              java-1.8.0-openjdk: []
          commands:
            01_update_yum:
              command: yum update -y
            02_create_xfs:
              command: mkfs -t xfs /dev/nvme1n1 && mkdir /opt/boomi && sh -c 'echo "/dev/nvme1n1 /opt/boomi xfs defaults,noatime 0 0" >> /etc/fstab' && mount -a
            03_set_hostname:
              command: ln -sf /opt/boomi/Atom_$(curl http://169.254.169.254/latest/meta-data/local-hostname | sed -r 's/[-.]+/_/g')/jre/bin/java /usr/bin/java && . ~/.bash_profile
            04_set_perms_and_create_dir:
              command: cd /usr/local && sudo mkdir boomi && sudo chown ec2-user:ec2-user boomi && cd /usr/local/boomi
            05_get_installer:
              command: wget -P /usr/local/boomi https://platform.boomi.com/atom/atom_install64.sh && chmod +x /usr/local/boomi/atom_install64.sh
            06_create_installer_dir:
              command: !Sub sudo mkdir -p ${BoomiInstallDir} && sudo chown -R ec2-user:ec2-user ${BoomiInstallDir} && cd /usr/local/boomi
            07_start_installer:
              command: !If
                - InstallTokenProvided
                - !Sub |
                  echo "installing via token: /usr/local/boomi/atom_install64.sh -q console -VinstallToken=${BoomiInstallToken} -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}" && /usr/local/boomi/atom_install64.sh -q console -VinstallToken=${BoomiInstallToken} -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}
                - !Sub |
                  echo "installing via username/password: /usr/local/boomi/atom_install64.sh -q console -Vusername=${BoomiUsername} -Vpassword=******** -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}" && /usr/local/boomi/atom_install64.sh -q console -Vusername=${BoomiUsername} -Vpassword=${BoomiPassword} -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}
            08_create_service:
              command: touch /lib/systemd/system/atom.service && echo "[Unit]
                Description=Dell Boomi Atom
                After=network.target
                RequiresMountsFor=/opt/boomi/Atom_atom
                [Service]
                Type=forking
                User=root
                Restart=always
                ExecStart=/opt/boomi/Atom_atom/bin/atom start
                ExecStop=/opt/boomi/Atom_atom/bin/atom stop
                ExecReload=/opt/boomi/Atom_atom/bin/atom restart
                [Install]
                WantedBy=multi-user.target" > /lib/systemd/system/atom.service
            09_service_perms:
              command: chown root:root /lib/systemd/system/atom.service && chmod 000644 /lib/systemd/system/atom.service
            10_start_service:
              command: systemctl enable atom && systemctl start atom

  EcInstanceAutorecoverAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:automate:${AWS::Region}:ec2:recover
      AlarmDescription: Recover instance if its status checks fail.
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Dimensions:
        - Name: InstanceId
          Value: !Ref AtomInstance
      EvaluationPeriods: 2
      Period: 60
      Statistic: Minimum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0

...
