AWSTemplateFormatVersion: "2010-09-09"
Description: Boomi Atom Installation Script. This creates a VPC, Public Subnets and Private Subnets, and stages a Dell Boomi Atom.

Parameters:
  KeyPairName:
    Description: Keyname for access to EC2 Instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing Keyname
  BastionSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
  InstanceType:
    Description: Boomi Host Instance Type
    Type: String
    Default: m5.xlarge
    AllowedValues:
      - m4.xlarge
      - m5.xlarge
      - r4.xlarge
      - r5.xlarge
      - c5.xlarge
  BoomiInstanceVolumeSize:
     Description: Atom Volume Size (In GiB). Size from 1GiB - 16TiB
     Type: Number
     Default: 100
  VPCID:
    Description: Select the VPC to deploy into.
    Type: AWS::EC2::VPC::Id
  PublicSubnet1ID:
    Description: Public Subnet ID 1 located in Availability Zone 1
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2ID:
    Description: Public Subnet ID 2 located in Availability Zone 2
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet1ID:
    Description: Private Subnet ID 1 located in Availability Zone 1
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: Private Subnet ID 2 located in Availability Zone 2
    Type: AWS::EC2::Subnet::Id
  BoomiUsername:
    Description: Please enter your Boomi User Name
    Type: String
  BoomiPassword:
     Description: Please enter your Boomi Account Password
     Type: String
     NoEcho: true
  BoomiAccountID:
     Description: Please enter your Boomi Account ID
     Type: String
  BoomiInstallDir:
     Description: Please enter an install directory for Boomi
     Type: String
     Default: /opt/boomi/

  AtomName:
     Description: Please enter a name for your Boomi Instance
     Type: String
     Default: atom1

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Network Configuration"
        Parameters:
         - VPCID
         - PublicSubnet1ID
         - PublicSubnet2ID
         - PrivateSubnet1ID
         - PrivateSubnet2ID
      -
        Label:
          default: "Amazon EC2 Configuration"
        Parameters:
          - InstanceType
          - KeyPairName
          - BoomiInstanceVolumeSize
      -
        Label:
          default: "Dell Boomi Atom Configuration"
        Parameters:
         - AtomName
         - BoomiAccountID
         - BoomiUsername
         - BoomiPassword
         - BoomiInstallDir
Mappings:
  AWSAMIRegionMap:
    AMI:
      AMZNLINUXHVM: amzn-ami-hvm-2018.03.0.20181129-x86_64-gp2
    us-east-1:
      AMZNLINUXHVM: ami-0ff8a91507f77f867
    us-west-2:
      AMZNLINUXHVM: ami-a0cfeed8
Resources:
  LoadBalancerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: boomi-elb
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 9090
          IpProtocol: tcp
          ToPort: 9090

  BoomiSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: boomi
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: BoomiSG
      SecurityGroupIngress:
        - FromPort: 22
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref BastionSecurityGroupID
          ToPort: 22
        - FromPort: 9090
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
          ToPort: 9090

  LaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - Ref: AWS::Region
        - AMZNLINUXHVM
      InstanceType:
        Ref: InstanceType
      BlockDeviceMappings:
       - DeviceName: "/dev/xvda"
         Ebs:
          VolumeType: "gp2"
          DeleteOnTermination: false
          VolumeSize:
            Ref: "BoomiInstanceVolumeSize"
      SecurityGroups:
       - !Ref BoomiSecurityGroup
      KeyName:
        Ref: KeyPairName
      UserData:
       Fn::Base64: !Sub |
        #!/bin/bash -x
          yum update -y
          yum install java-1.8.0-openjdk -y
          echo JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk.x86_64 >> /home/ec2-user/.bash_profile
          echo export PATH=$JAVA_HOME/bin:$PATH >> /home/ec2-user/.bash_profile
          . ~/.bash_profile
          cd /usr/local
          sudo mkdir boomi
          sudo chown ec2-user:ec2-user boomi
          cd /usr/local/boomi
          wget https://platform.boomi.com/atom/atom_install64.sh
          chmod +x atom_install64.sh
          sudo mkdir ${BoomiInstallDir}
          sudo chown ec2-user:ec2-user ${BoomiInstallDir}
          ./atom_install64.sh -q console -BoomiUsername=${BoomiUsername} -BoomiPassword=${BoomiPassword}  -AtomName=${AtomName} -BoomiAccountId=${BoomiAccountID} -dir ${BoomiInstallDir}
  AutoScaling:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
      - Ref: PrivateSubnet1ID
      - Ref: PrivateSubnet2ID
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      Cooldown: '300'
      HealthCheckGracePeriod: 300
      HealthCheckType: ELB
      LoadBalancerNames: [ Ref: ElasticLoadBalancer ]
      Tags:
        - PropagateAtLaunch: true
          Value: Boomi
          Key: Name
  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets:
      - Ref: PublicSubnet1ID
      - Ref: PublicSubnet2ID
      CrossZone: true
      Listeners:
      - LoadBalancerPort: '22'
        InstancePort: '22'
        Protocol: TCP
      HealthCheck:
        Target: TCP:22
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup